### ISSUE TITLE
Fancier output

### ISSUE THREAD

**Issue by evanp** [fuzzy-ai/perjury#1]
It would be nice to use some ANSI codes or whatever to make the
fancier output like vows.js does.

**Comment by mattfogel** [comment]
░░░░░▄▄▄▄▀▀▀▀▀▀▀▀▄▄▄▄▄▄░░░░░░░
░░░░░█░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░▀▀▄░░░░ 
░░░░█░░░▒▒▒▒▒▒░░░░░░░░▒▒▒░░█░░░ 
░░░█░░░░░░▄██▀▄▄░░░░░▄▄▄░░░░█░░ 
░▄▀▒▄▄▄▒░█▀▀▀▀▄▄█░░░██▄▄█░░░░█░ 
█░▒█▒▄░▀▄▄▄▀░░░░░░░░█░░░▒▒▒▒▒░█ 
█░▒█░█▀▄▄░░░░░█▀░░░░▀▄░░▄▀▀▀▄▒█ 
░█░▀▄░█▄░█▀▄▄░▀░▀▀░▄▄▀░░░░█░░█░ 
░░█░░░▀▄▀█▄▄░█▀▀▀▄▄▄▄▀▀█▀██░█░░ 
░░░█░░░░██░░▀█▄▄▄█▄▄█▄████░█░░░ 
░░░░█░░░░▀▀▄░█░░░█░█▀██████░█░░ 
░░░░░▀▄░░░░░▀▀▄▄▄█▄█▄█▄█▄▀░░█░░ 
░░░░░░░▀▄▄░▒▒▒▒░░░░░░░░░░▒░░░█░ 
░░░░░░░░░░▀▀▄▄░▒▒▒▒▒▒▒▒▒▒░░░░█░ 
░░░░░░░░░░░░░░▀▄▄▄▄▄░░░░░░░░█░░

**Comment by evanp** [comment]
Deferring in favor of vowsjs/vows#387 and vowsjs/vows#388
