### ISSUE TITLE
Return a Promise from a batch topic

### ISSUE THREAD

**Issue by strugee** [fuzzy-ai/perjury#30]
I should be able to return a Promise from a batch topic and have Perjury do the Right Thing:tm:.

**Comment by evanp** [comment]
What does vowsjs do in this situation?

**Comment by strugee** [comment]
They don't handle it specially either, AFAICT. There's an open PR to add it; see vowsjs/vows#364.

**Comment by strugee** [comment]
No references to them in the code, although the commit history turns up some stuff: https://github.com/vowsjs/vows/search?q=promise&type=Code&utf8=%E2%9C%93
