### ISSUE TITLE
ChalkReporter

### ISSUE THREAD

**Issue by evanp** [fuzzy-ai/perjury#39]
We should have a reporter that does colorized output (green/yellow/red)
for the different test results, using the `chalk` package.

**Comment by strugee** [comment]
Seems a shame to reinvent this all ourselves. I wonder if we could steal^D^Drip out Vows' reporter for ourselves. Or find a bunch of modules that take something reasonably common, like TAP or something.

**Comment by evanp** [comment]
Closing this out in favour of vowsjs/vows#387
